version: '2.4'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - java-discord-help-bot-volume-db:/var/lib/postgresql/data
      - java-discord-help-bot-volume-db-backup:/backup
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - ./shared:/shared
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 1s
      timeout: 1s
      retries: 30
    labels:
      - docker-volume-backup.exec-label=java-discord-help-bot
      - docker-volume-backup.archive-pre=/bin/bash -c '/shared/make-backup.sh'
      - command-runner.group=java-discord-help-bot
      - command-runner.shell=/bin/bash -c
      - command-runner.command=/shared/restore-backup.sh;

