---
discord:
  token: ${JAVA_DISCORD_HELP_BOT_DISCORD_TOKEN}
  mainGuildId: 448934652992946176

server:
  port: 9015

app-reference:
  protocol: http
  address: host.docker.internal

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    username: ${POSTGRES_APP_USER}
    password: ${POSTGRES_APP_PASSWORD}
    url: ${POSTGRES_URL}

gitea:
  token: ${JAVA_DISCORD_HELP_BOT_GITEA_TOKEN}
  protocol: http
  address: host.docker.internal
  port: 3001
  branch-name: main
  failure-limit: 3
  admin:
    username: ${GITEA_ADMIN_USER_NAME}
    password: ${GITEA_ADMIN_USER_PASSWORD}
    email: ${GITEA_ADMIN_EMAIL}
  git:
    repoPath: /Users/gener/OneDrive/Documents/gitea/
