---
discord:
  mainGuildId: 448934652992946176

server:
  port: 9015

app-reference:
  protocol: http
  address: host.docker.internal

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    username: d
    password: d
    url: jdbc:postgresql://localhost:5432/discord_help_bot

gitea:
  protocol: http
  address: localhost
  port: 3000
  branch-name: main
  failure-limit: 3
  git:
    username: d
    password: d
    email: d@d.d
    repoPath: /Users/gener/OneDrive/Documents/gitea/
