---
discord:
  token: ${JAVA_DISCORD_HELP_BOT_DISCORD_TOKEN}
  mainGuildId: 448934652992946176

server:
  port: 9015

app-reference:
  protocol: http
  address: host.docker.internal
  url: ${app-reference.protocol}://${app-reference.address}:${server.port}

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    username: ${POSTGRES_APP_USER}
    password: ${POSTGRES_APP_PASSWORD}
    url: ${POSTGRES_URL}
  flyway:
    url: ${POSTGRES_URL}
    user: ${POSTGRES_FLYWAY_USER}
    password: ${POSTGRES_FLYWAY_PASSWORD}
    defaultSchema: public

gitea:
  token: ${JAVA_DISCORD_HELP_BOT_GITEA_TOKEN}
  protocol: http
  address: host.docker.internal
  port: 3001
  url: ${gitea.protocol}://${gitea.address}:${gitea.port}
  branch-name: main
  failure-limit: 3
  admin:
    username: ${GITEA_ADMIN_USER_NAME}
    password: ${GITEA_ADMIN_USER_PASSWORD}
    email: ${GITEA_ADMIN_EMAIL}
  git:
    repoPath: /Users/gener/OneDrive/Documents/gitea/
