version: '2.4'

services:
  db:
    container_name: java-discord-help-bot-db
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - java-discord-help-bot-volume-db:/var/lib/postgresql/data
      - java-discord-help-bot-volume-db-backup:/backup
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      - docker-volume-backup.exec-label=java-discord-help-bot
      - docker-volume-backup.archive-pre=/bin/bash -c 'mkdir -p /backup/current & pg_dumpall -c -U ${POSTGRES_USER} > /backup/current/dump.sql'
      - command-runner.group=java-discord-help-bot
      - command-runner.shell=/bin/sh -c
      - command-runner.command=mc mirror --overwrite /backup/archived minio/loki-data; rm -r /backup/archived
