version: '2.4'

services:
  java-discord-help-bot-db:
    container_name: java-discord-help-bot-db
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - java-discord-help-bot-volume-db:/var/lib/postgresql/data
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      - "docker-volume-backup.archive-pre=/bin/bash -c 'rm -r /backup & mkdir -p /backup & pg_dumpall -c -U ${POSTGRES_USER} > /backup/dump_`date +%d-%m-%Y_%H_%M_%S`.sql'"

volumes:
  java-discord-help-bot-volume-db: