version: '3.8'

services:
  java-discord-help-bot-db:
    container_name: java-discord-help-bot-db
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - java-discord-help-bot-volume-db:/var/lib/postgresql/data
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 3

volumes:
  java-discord-help-bot-volume-db: