version: '2.4'

services:
  app:
    container_name: java-discord-help-bot-app
    image: generaltao725/java-discord-help-bot:latest
    ports:
      - "9015:9015"
    env_file:
      - ../.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: curl localhost:9015/actuator/health
      interval: 1s
      timeout: 1s
      retries: 30