# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    env:
      DEPLOYMENT_LOCALHOST_NAME: localhost

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Bump version and push tag
      id: github_tag_action
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: test
      run: echo ============== ${{ steps.github_tag_action.outputs.new_tag  }} bruh

#    - name: Build with Maven
#      run: mvn -B -P docker clean package -DskipTests

#    - name: Prepare for tests with Maven
#      run: mvn -P automation clean install "-Ddiscord.token=${{ secrets.AUTOMATION_TEST_TOKEN }}" -DskipTests=true

#    - name: Login to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Run tests with Maven
#      run: mvn -Dtest=discord.automation.runners.CucumberRunnerIT test

#    - name: Push
#      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices-design-patterns:authentication-service
    # # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
